<a href="https://colab.research.google.com/github/Kaveshnikov/FMPHNeuralNetworks/blob/master/C01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
# Neural Networks (2-AIN-132/15), FMFI UK BA
# (c) Tomas Kuzma, Juraj Holas, Peter Gergel, Endre Hamerlik, Štefan Pócoš, Iveta Bečková 2017-2024

import numpy as np
import matplotlib.pyplot as plt


## Generate data
# number of points
N = 100

# generate x values
x = np.arange(N).reshape(-1, 1)   # FIXME: vector [0, 1, 2, ..., N-1]
x

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29],
       [30],
       [31],
       [32],
       [33],
       [34],
       [35],
       [36],
       [37],
       [38],
       [39],
       [40],
       [41],
       [42],
       [43],
       [44],
       [45],
       [46],
       [47],
       [48],
       [49],
       [50],
       [51],
       [52],
       [53],
       [54],
       [55],
       [56],
       [57],
       [58],
       [59],
       [60],
       [61],
       [62],
       [63],
       [64],
       [65],
       [66],
       [67],
       [68],
       [69],
       [70],
       [71],
       [72],
       [73],
       [74],
       [75],
       [76],

In [3]:
# generate random slope (k) and shift (q)
k = np.random.rand()   # FIXME: random number from normal distribution
k

-1.1477770347537786

In [4]:
q = np.random.randn()   # FIXME: random number from uniform distribution
q

2.158313865172439

In [5]:
# calculate y values
y = k * x + q   # FIXME: according to slides
y

array([[ 2.15831387],
       [ 2.87543908],
       [ 3.5925643 ],
       [ 4.30968952],
       [ 5.02681474],
       [ 5.74393996],
       [ 6.46106518],
       [ 7.1781904 ],
       [ 7.89531562],
       [ 8.61244083],
       [ 9.32956605],
       [10.04669127],
       [10.76381649],
       [11.48094171],
       [12.19806693],
       [12.91519215],
       [13.63231736],
       [14.34944258],
       [15.0665678 ],
       [15.78369302],
       [16.50081824],
       [17.21794346],
       [17.93506868],
       [18.6521939 ],
       [19.36931911],
       [20.08644433],
       [20.80356955],
       [21.52069477],
       [22.23781999],
       [22.95494521],
       [23.67207043],
       [24.38919565],
       [25.10632086],
       [25.82344608],
       [26.5405713 ],
       [27.25769652],
       [27.97482174],
       [28.69194696],
       [29.40907218],
       [30.1261974 ],
       [30.84332261],
       [31.56044783],
       [32.27757305],
       [32.99469827],
       [33.71182349],
       [34

In [7]:
# add noise
rng = np.random.default_rng()
y += rng.standard_normal(y.size).reshape(-1, 1)  # FIXME: add vector of random values from normal distribution
y

array([[ 1.10359019],
       [ 4.56960227],
       [ 1.27147338],
       [ 2.84927172],
       [ 5.79736492],
       [ 5.7715304 ],
       [ 5.35815094],
       [ 7.31747089],
       [ 7.68332119],
       [ 9.42712305],
       [10.80293473],
       [10.98592463],
       [10.2402863 ],
       [10.85022985],
       [13.33368   ],
       [15.97597629],
       [14.06072473],
       [13.77867901],
       [16.06167771],
       [14.93911257],
       [16.80849139],
       [17.53544515],
       [16.4180891 ],
       [20.90989233],
       [20.1322291 ],
       [19.23485539],
       [20.10253261],
       [19.67153731],
       [22.43688185],
       [24.05694653],
       [24.20297752],
       [25.91902353],
       [24.61118315],
       [23.17035707],
       [28.10717533],
       [27.08809699],
       [26.12931767],
       [28.11303506],
       [29.73418701],
       [28.91450051],
       [31.48728438],
       [31.92713764],
       [32.26301582],
       [32.21744175],
       [34.51644036],
       [32

In [10]:
# plot all points
plt.scatter(x, y)

In [11]:
## Find k and q using linear regression
# first append ones to x
X = np.concatenate((x, np.ones((x.size, 1))), axis=1)  # FIXME: X should be matrix of two columns: first column is vector x, second column are ones
X

array([[ 0.,  1.],
       [ 1.,  1.],
       [ 2.,  1.],
       [ 3.,  1.],
       [ 4.,  1.],
       [ 5.,  1.],
       [ 6.,  1.],
       [ 7.,  1.],
       [ 8.,  1.],
       [ 9.,  1.],
       [10.,  1.],
       [11.,  1.],
       [12.,  1.],
       [13.,  1.],
       [14.,  1.],
       [15.,  1.],
       [16.,  1.],
       [17.,  1.],
       [18.,  1.],
       [19.,  1.],
       [20.,  1.],
       [21.,  1.],
       [22.,  1.],
       [23.,  1.],
       [24.,  1.],
       [25.,  1.],
       [26.,  1.],
       [27.,  1.],
       [28.,  1.],
       [29.,  1.],
       [30.,  1.],
       [31.,  1.],
       [32.,  1.],
       [33.,  1.],
       [34.,  1.],
       [35.,  1.],
       [36.,  1.],
       [37.,  1.],
       [38.,  1.],
       [39.,  1.],
       [40.,  1.],
       [41.,  1.],
       [42.,  1.],
       [43.,  1.],
       [44.,  1.],
       [45.,  1.],
       [46.,  1.],
       [47.,  1.],
       [48.,  1.],
       [49.,  1.],
       [50.,  1.],
       [51.,  1.],
       [52.,

In [12]:
# then find params
k_pred, q_pred = (X.T @ X)**(-1), X.T @ y   # FIXME: according to slides
(k_pred, q_pred)

(array([[3.04553068e-06, 2.02020202e-04],
        [2.02020202e-04, 1.00000000e-02]]),
 array([[245548.59192843],
        [  3760.89127342]]))

In [13]:
# predict ys and plot as a line
y_pred = k_pred @ x + q_pred   # FIXME: according to slides
y_pred

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 100 is different from 2)

In [14]:
# plot predicted
plt.plot(x, y_pred, 'r')

NameError: name 'y_pred' is not defined